name: flutter_sfmc_platform_interface
description: A common platform interface for the flutter_sfmc plugin.
version: 1.0.0

environment:
  sdk: ">=3.0.0 <4.0.0"
  flutter: ">=3.0.0"

dependencies:
  flutter:
    sdk: flutter
  plugin_platform_interface: ^2.1.0

dev_dependencies:
  flutter_test:
    sdk: flutter
  pigeon: ^10.1.0
  very_good_analysis: ^5.0.0+1
